@startmindmap client-360

!include ../include/themes/light.puml
!option handwritten false

<style>
mindmapDiagram {
  node {
    Padding 5
    Margin 15
    BackGroundColor BG_MAIN_COLOR
    LinkUnderline false
  }
  boxless {
    FontColor BG_MAIN_COLOR
  }
  rootNode {
    Padding 15
    FontStyle Italic
  }
  leafNode {
    Padding 1
    FontSize 15
  }
  arrow {
    Color ARROW_COLOR
    LineThickness 1.5
  }
  depth(1) {
    FontSize 15
    FontColor #red
    HyperlinkColor #red
  }
  depth(2) {
    FontSize 14
  }
  depth(3) {
    FontSize 13
  }
  depth(4) {
    FontSize 12
  }
}
</style>

+ [[ /use-case/client-360/ Client 360 ]]
++_ [[ /use-case/client-360/know-your-customer/ KYC ]]
+++_ [[ /use-case/client-360/know-your-customer/anti-money-laundering/ Anti Money Laundering (AML) ]]
++++_ [[ /use-case/client-360/know-your-customer/anti-money-laundering/correspondent-based-aml/ Correspondent-based AML ]]
++++_ [[ /use-case/client-360/know-your-customer/anti-money-laundering/network-based-aml/ Network-based AML ]]
++++_ [[ /use-case/client-360/know-your-customer/anti-money-laundering/transaction-based-aml/ Transaction/Finance-based AML ]]
+++_ [[ /use-case/client-360/know-your-customer/identification-verification/ Identification Verification ]]
+++_ [[ /use-case/client-360/know-your-customer/peps/ Politically Exposed Persons (PEPs) ]]
+++_ [[ /use-case/client-360/know-your-customer/crime-records/ Crime Records ]]
+++_ [[ /use-case/client-360/know-your-customer/sanctions/ Sanctions ]]
+++_ [[ /use-case/client-360/know-your-customer/risk-management/ Risk Management ]]
+++_ [[ /use-case/client-360/know-your-customer/high-net-worth-individuals/ High Net Worth Individuals (HNWI) ]]
+++_ [[ /use-case/client-360/know-your-customer/gdpr/ GDPR ]]
+++_ [[ /use-case/client-360/know-your-customer/core-record-management/ Core Record Management ]]
++++_ [[ /use-case/client-360/know-your-customer/core-record-management/countries/ Countries ]]
++++_ [[ /use-case/client-360/know-your-customer/core-record-management/regions/ Regions ]]
++++_ [[ /use-case/client-360/know-your-customer/core-record-management/jurisdictions/ Jurisdictions ]]
++++_ [[ /use-case/client-360/know-your-customer/core-record-management/legal-entities/ Legal Entities ]]
++++_ [[ /use-case/client-360/know-your-customer/core-record-management/locations/ Locations ]]
++++_ [[ /use-case/client-360/know-your-customer/core-record-management/buildings/ Buildings ]]
++++_ [[ /use-case/client-360/know-your-customer/core-record-management/addresses/ Addresses ]]
++++_ [[ /use-case/client-360/know-your-customer/core-record-management/audit/ Audit ]]
++_ [[ /use-case-client-360/relationships-and-connections/ Relationships & Connections ]]
+++_ [[ /use-case-client-360/relationships-and-connections/business-connections/ Business Connections ]]
+++_ [[ /use-case-client-360/relationships-and-connections/family-connections/ Family Connections ]]
+++_ [[ /use-case-client-360/relationships-and-connections/social-connections/ Social Connections ]]
+++_ [[ /use-case-client-360/relationships-and-connections/political-connections/ Political Connections ]]
++_ [[ /use-case-client-360/social-media/ Social Media ]]
+++_ [[ /use-case-client-360/social-media/social-graph/ Social Graph ]]
+++_ [[ /use-case-client-360/social-media/social-graph/ Interest Graph ]]
++_ ...many others...
@endmindmap
