@startmindmap

!include ../include/themes/light.puml

+ [[ /use-case/legal-entity-management/ Legal Entity Management ]]
++_ [[ /use-case/legal-entity-management/identification-and-registration/ Identification & Registration ]]
+++_ [[ /use-case/legal-entity-management/identification-and-registration/legal-form/ Legal Form ]]
+++_ [[ /use-case/legal-entity-management/identification-and-registration/business-registration/ Business Registration ]]
+++_ [[ /use-case/legal-entity-management/identification-and-registration/commercial-register/ Commercial Register ]]
+++_ [[ /use-case/legal-entity-management/identification-and-registration/classification/ Classification ]]
++_ [[ /use-case/legal-entity-management/corporate-governance/ Corporate Governance ]]
+++_ [[ /use-case/legal-entity-management/corporate-governance/directorships/ Directorships ]]
+++_ [[ /use-case/legal-entity-management/corporate-governance/signatories/ Signatories ]]
+++_ [[ /use-case/legal-entity-management/corporate-governance/organizational-structure/ Organizational Structure ]]
++_ [[ /use-case/legal-entity-management/ownership-and-capital-structure/ Ownership & Capital Structure ]]
+++_ [[ /use-case/legal-entity-management/ownership-and-capital-structure/ownership/ Ownership ]]
+++_ [[ /use-case/legal-entity-management/ownership-and-capital-structure/control/ Control ]]
+++_ [[ /use-case/legal-entity-management/ownership-and-capital-structure/shares/ Shares & Ownership ]]
+++_ [[ /use-case/legal-entity-management/ownership-and-capital-structure/share-capital/ Share Capital ]]
+++_ [[ /use-case/legal-entity-management/ownership-and-capital-structure/issued-capital/ Issued Capital ]]
+++_ [[ /use-case/legal-entity-management/ownership-and-capital-structure/corporate-actions/ Corporate Actions ]]
++++_ [[ /use-case/legal-entity-management/ownership-and-capital-structure/corporate-actions/merger-and-acquisition-history/ Merger & Acquisition History ]]
++++_ [[ /use-case/legal-entity-management/ownership-and-capital-structure/corporate-actions/spin-offs/ Spin-offs ]]
++++_ [[ /use-case/legal-entity-management/ownership-and-capital-structure/corporate-actions/parents-and-subsidiaries/ Parents and Subsidiaries ]]
++++_ [[ /use-case/legal-entity-management/ownership-and-capital-structure/corporate-actions/stock-splits/ Stock Splits ]]
++++_ [[ /use-case/legal-entity-management/ownership-and-capital-structure/corporate-actions/dividends/ Dividends ]]
++_ [[ /use-case/legal-entity-management/financial-information/ Financial Information ]]
+++_ [[ /use-case/legal-entity-management/financial-information/assets/ Assets ]]
+++_ [[ /use-case/legal-entity-management/financial-information/fundamentals/ Fundamentals ]]
+++_ [[ /use-case/legal-entity-management/financial-information/earnings-estimates/ Earnings Estimates ]]
+++_ [[ /use-case/legal-entity-management/financial-information/ratings/ Ratings ]]
+++_ [[ /use-case/legal-entity-management/financial-information/liability-terms/ Liability Terms ]]
++_ [[ /use-case/legal-entity-management/lifecycle-and-status/ Lifecycle & Status ]]
+++_ [[ /use-case/legal-entity-management/lifecycle-and-status/dissolution/ Dissolution ]]
+++_ [[ /use-case/legal-entity-management/lifecycle-and-status/liquidation/ Liquidation ]]
++_ [[ /use-case/legal-entity-management/contact-and-location-information/ Contact & Location Information ]]
+++_ [[ /use-case/legal-entity-management/contact-and-location-information/contacts/ Contacts ]]
+++_ [[ /use-case/legal-entity-management/contact-and-location-information/addresses/ Addresses ]]
++_ [[ /use-case/legal-entity-management/compliance-and-documentation/ Compliance & Documentation ]]
+++_ [[ /use-case/legal-entity-management/compliance-and-documentation/compliance/ Compliance ]]
+++_ [[ /use-case/legal-entity-management/compliance-and-documentation/documents/ Documents ]]
++_ [[ /use-case/legal-entity-management/supporting-information/ Supporting Information ]]
+++_ [[ /use-case/legal-entity-management/supporting-information/currencies/ Currencies ]]
@endmindmap
