@startmindmap

!include ../include/themes/light.puml

+_ [[ /use-case/construction-project-quotations/opportunity-and-tender-intake/ Opportunity & Tender Intake ]]
++_ [[ /use-case/construction-project-quotations/opportunity-and-tender-intake/rfp-rfq-intake/ RFP/RFQ Intake & Document Catalog ]]
++_ [[ /use-case/construction-project-quotations/opportunity-and-tender-intake/bid-no-bid-decisioning/ Bid/No-Bid Decisioning ]]
++ [[ /use-case/construction-project-quotations/opportunity-and-tender-intake/site-visit-and-existing-conditions/ Site Visit & Existing Conditions ]]
--_ [[ /use-case/construction-project-quotations/ Complex Construction Project Quotations ]]
@endmindmap


