@startmindmap

!include ../include/themes/light.puml

+_ [[ /use-case/client-360/ Client 360 ]]
++_ [[ /use-case/client-360/relationships-and-connections/ Relationships & Connections ]]
+++_ [[ /use-case/client-360/relationships-and-connections/business-connections/ Business Connections ]]
+++_ [[ /use-case/client-360/relationships-and-connections/family-connections/ Family Connections ]]
+++ [[ /use-case/client-360/relationships-and-connections/social-connections/ Social Connections ]]
+++_ [[ /use-case/client-360/relationships-and-connections/political-connections/ Political Connections ]]
@endmindmap

