@startmindmap

!include ../include/themes/light.puml

+_ [[ /use-case/client-360/ Client 360 ]]
++_ [[ /use-case/client-360/social-media/ Social Media ]]
+++ [[ /use-case/client-360/social-media/social-graph/ Social Graph ]]
+++_ [[ /use-case/client-360/social-media/interest-graph/ Interest Graph ]]
@endmindmap

