@startmindmap

!include ../include/themes/light.puml

+_ [[ /use-case/construction-project-quotations/estimating-and-pricing/ Estimating & Pricing ]]
++_ [[ /use-case/construction-project-quotations/estimating-and-pricing/quantity-takeoff/ Quantity Takeoff (2D/3D/BIM) ]]
++ [[ /use-case/construction-project-quotations/estimating-and-pricing/unit-rates-and-cost-libraries/ Unit Rates & Cost Libraries ]]
++_ [[ /use-case/construction-project-quotations/estimating-and-pricing/labor-productivity-and-crew-modeling/ Labor Productivity & Crew Modeling ]]
++_ [[ /use-case/construction-project-quotations/estimating-and-pricing/indirects-overheads-general-conditions/ Indirects, Overheads & General Conditions ]]
++_ [[ /use-case/construction-project-quotations/estimating-and-pricing/contingency-and-escalation/ Contingency & Escalation ]]
++_ [[ /use-case/construction-project-quotations/estimating-and-pricing/pricing-strategy-margin-markups/ Pricing Strategy (Margin/Markups) ]]
--_ [[ /use-case/construction-project-quotations/ Complex Construction Project Quotations ]]
@endmindmap


