@startmindmap

!include ../../../include/themes/light.puml

+ [[ /use-case/construction-project-quotations/supply-chain-and-subcontractors/bid-leveling/ Bid Leveling & Comparative Analysis ]]
@endmindmap
