@startmindmap supply-chain-and-subcontractors

!include ../../../include/themes/light.puml

+ [[ /use-case/construction-project-quotations/supply-chain-and-subcontractors/ Supply Chain & Subcontractors ]]
--_ [[ /use-case/construction-project-quotations/ Complex Construction Project Quotations ]]
---_ [[ /use-case/construction-project-quotations/estimating-and-pricing/ Estimating & Pricing ]]
---_ [[ /use-case/construction-project-quotations/knowledge-capture-and-improvement/ Knowledge Capture & Continuous Improvement ]]
---_ [[ /use-case/construction-project-quotations/opportunity-and-tender-intake/ Opportunity & Tender Intake ]]
---_ [[ /use-case/construction-project-quotations/proposal-submission-and-negotiation/ Proposal & Negotiation ]]
---_ [[ /use-case/construction-project-quotations/risk-compliance-and-contracts/ Risk, Compliance & Contracts ]]
---_ [[ /use-case/construction-project-quotations/scope-and-requirements/ Scope & Requirements ]]
++_ [[ /use-case/construction-project-quotations/supply-chain-and-subcontractors/bid-leveling/ Bid Leveling & Comparative Analysis ]]
++_ [[ /use-case/construction-project-quotations/supply-chain-and-subcontractors/subcontractor-bid-solicitation-and-comparison/ Subcontractor Bid Solicitation & Comparison ]]
++_ [[ /use-case/construction-project-quotations/supply-chain-and-subcontractors/subcontractor-scope-packages/ Subcontractor Scope Packages ]]
++_ [[ /use-case/construction-project-quotations/supply-chain-and-subcontractors/supplier-rfqs-and-material-pricing/ Supplier RFQs & Material Pricing ]]
@endmindmap
