@startmindmap

!include ../../../include/themes/light.puml

+ [[ /use-case/construction-project-quotations/supply-chain-and-subcontractors/supplier-rfqs-and-material-pricing/ Supplier RFQs & Material Pricing ]]
@endmindmap
