@startmindmap fundamentals

!include ../../../../include/themes/light.puml

+[ [[ /use-case/legal-entity-management/financial-information/fundamentals/ Fundamentals ]]
--_ [[ /use-case/legal-entity-management/financial-information/ Financial Information ]]
@endmindmap
