@startmindmap vendor-onboarding

!include ../../../../../include/themes/light.puml

+[ [[ /use-case/supply-chain-management/vendor-management/vendor-vetting-and-onboarding/vendor-onboarding/ Vendor Onboarding ]]
--_ [[ /use-case/supply-chain-management/vendor-management/vendor-vetting-and-onboarding/ Vendor Vetting & Onboarding ]]
@endmindmap
