@startmindmap shares

!include ../../../../include/themes/light.puml

+[ [[ /use-case/legal-entity-management/ownership-and-capital-structure/shares/ Shares ]]
--_ [[ /use-case/legal-entity-management/ownership-and-capital-structure/ Ownership & Capital Structure ]]
@endmindmap
