@startmindmap compliance-and-documentation

!include ../../../include/themes/light.puml

+[ [[ /use-case/legal-entity-management/compliance-and-documentation/ Compliance & Documentation ]]
--_ [[ /use-case/legal-entity-management/ Legal Entity Management ]]
++_ [[ /use-case/legal-entity-management/compliance-and-documentation/compliance/ Compliance ]]
++_ [[ /use-case/legal-entity-management/compliance-and-documentation/documents/ Documents ]]
@endmindmap
