title: Estimating & Pricing
nav:
- index.md
- contingency-and-escalation.md
- indirects-overheads-general-conditions.md
- labor-productivity-and-crew-modeling.md
- pricing-strategy-margin-markups.md
- quantity-takeoff.md
- unit-rates-and-cost-libraries.md
