site_name: EKG/Usecases
site_description: Use cases for the Enterprise Knowledge Graph
repo_name: 'ekgf/ekg-use-cases'
repo_url: https://github.com/ekgf/ekg-use-cases
site_url: https://use-cases.ekgf.org
site_dir: site
site_author: Enterprise Knowledge Graph Foundation
copyright: Copyright &copy; 2022 Enterprise Knowledge Graph Foundation
edit_uri: ''
# Navigation
# nav: omitted, because we're using the awesome-pages plugin (https://squidfunk.github.io/mkdocs-material/plugins/awesome-pages/)
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  language: en
  custom_dir: docs-overrides/
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: ekgf-logo-reversed
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: light-blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: deep orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - search.highlight
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - content.code.annotate
extra:
  generator: false
  giscus:
    repo_id: 'MDEwOlJlcG9zaXRvcnkzMTk3MTE4MzM='
    category:
      name: 'General'
      id: 'DIC_kwDOEw5qWc4CA98b'
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/EKG_Foundation
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/EKGF
    - icon: fontawesome/brands/github
      link: https://github.com/EKGF/ekg-use-cases
extra_javascript:
  - "javascript/images_dark.js"
  - "javascript/refresh_on_toggle_dark_light.js"
  - "https://cdn.jsdelivr.net/gh/rod2ik/cdn@main/mkdocs/javascripts/mkdocs-graphviz.js"
plugins:
  - include-markdown
  - git-revision-date
  - search:
      lang:
        - en
  - awesome-pages:
      filename: .pages.yaml
      collapse_single_pages: false
      strict: true
  - exclude:
      glob:
        - "*.tmp"
        - "*.sparql"
        - "*.gz"
      regex:
        - '.*\.(tmp|bin|tar)$'
        - '_.*\.md$'
  - macros:
      module_name: docs/main
  - build_plantuml:
      render: "server" # or "local" for local rendering
      bin_path: "/usr/local/bin/plantuml" # ignored when render: server
      server: "http://www.plantuml.com/plantuml" # offical plantuml server
      output_format: "svg" # or "png"
      diagram_root: "docs/diagrams" # should reside under docs_dir
      output_folder: "out"
      input_folder: "src"
      input_extensions: "" # comma separated list of extensions to parse, by default every file is parsed
      theme_enabled: true
      theme_folder: "include/themes"
      theme_light: "light.puml"
      theme_dark: "dark.puml"
#  - exclude:
#      glob:
#        - diagrams/include/C4/*

markdown_extensions:
  - toc:
      permalink: true
  - mdx_spanner
  - def_list
  - abbr
  - admonition
  - mdx_emdash
  - attr_list
  - footnotes
  - tables
  - md_in_html
  - mkdocs_graphviz
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path:
        - .
        - docs
        - Queries/SPARQL/
      check_paths: true
      auto_append:
        - abbreviations.md
  - pymdownx.details
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
