@startmindmap dissolution

!include ../../../../include/themes/light.puml

+[ [[ /use-case/legal-entity-management/lifecycle-and-status/dissolution/ Dissolution ]]
--_ [[ /use-case/legal-entity-management/lifecycle-and-status/ Lifecycle & Status ]]
@endmindmap
