@startmindmap regions

!include ../../../../../include/themes/light.puml

+[ [[ /use-case/client-360/know-your-customer/core-record-management/regions/ Regions ]]
--_ [[ /use-case/client-360/know-your-customer/core-record-management/ Core Record Management ]]
@endmindmap
