!define BG_MAIN_COLOR      #4051b5
!define BG_SECONDARY_COLOR #4051b5
!define BG_PACKAGE_COLOR   #4051b5
!define BORDER_COLOR       #ff6f00
!define FONT_COLOR         #ffffff

skinparam backgroundColor #transparent

' include the general skinparams for both, light and dark
' to overwrite with the given settings
!include general.puml

skinparam state {
    BackgroundColor #4051b5
    FontColor #ffffff
    AttributeFontColor #ffffff
    ArrowColor #ff6f00
    BorderColor #ff6f00
}

skinparam class {
    BackgroundColor #4051b5
    FontColor #ffffff
    BorderColor #ff6f00
}

' Mindmap specific styling
skinparam node {
    BackgroundColor #4051b5
    FontColor #ffffff
    BorderColor #ff6f00
}

skinparam arrowThickness 1
