@startmindmap

!include ../../../include/themes/light.puml

+ [[ /use-case/construction-project-quotations/estimating-and-pricing/indirects-overheads-general-conditions/ Indirects, Overheads & General Conditions ]]
@endmindmap
