@startmindmap

!include ../../../include/themes/light.puml

+ [[ /use-case/construction-project-quotations/estimating-and-pricing/labor-productivity-and-crew-modeling/ Labor Productivity & Crew Modeling ]]
@endmindmap
