@startmindmap

!include ../../../include/themes/light.puml

+ [[ /use-case/construction-project-quotations/knowledge-capture-and-improvement/document-ingestion-and-knowledge-extraction/ Document Ingestion & Knowledge Extraction ]]
@endmindmap
