@startmindmap

!include ../../../../include/themes/light.puml

+ [[ /use-case/supply-chain-management/vendor-management/vendor-vetting-and-onboarding/vendor-due-diligence/ Vendor Due Diligence ]]
@endmindmap
