@startmindmap sanctions

!include ../../../../include/themes/light.puml

+[ [[ /use-case/client-360/know-your-customer/sanctions/ Sanctions ]]
--_ [[ /use-case/client-360/know-your-customer/ Know Your Customer ]]
@endmindmap
