@startmindmap signatories

!include ../../../../include/themes/light.puml

+ [[ /use-case/legal-entity-management/corporate-governance/signatories/ Signatories ]]
--_ [[ /use-case/legal-entity-management/corporate-governance/ Corporate Governance ]]
---_ [[ /use-case/legal-entity-management/corporate-governance/directorships/ Directorships ]]
---_ [[ /use-case/legal-entity-management/corporate-governance/organizational-structure/ Organizational Structure ]]
@endmindmap
