@startmindmap

!include ../../../include/themes/light.puml

+ [[ /use-case/construction-project-quotations/risk-compliance-and-contracts/regulatory-safety-environmental-compliance/ Regulatory, Safety & Environmental Compliance ]]
@endmindmap
