@startmindmap content-relationships

!include ../../../include/themes/light.puml

+ [[ /use-case/recommendation-engine/content-relationships/ Content Relationships ]]
--_ [[ /use-case/recommendation-engine/ Recommendation Engine ]]
---_ [[ /use-case/recommendation-engine/behavioral-patterns/ Behavioral Patterns ]]
@endmindmap
