@startmindmap

!include ../../../../include/themes/light.puml

+ [[ /use-case/supply-chain-management/vendor-management/vendor-relationship-management/vendor-contracts/ Vendor Contracts ]]
@endmindmap
