@startmindmap pricing-strategy-margin-markups

!include ../../../../include/themes/light.puml

+[ [[ /use-case/construction-project-quotations/estimating-and-pricing/pricing-strategy-margin-markups/ Pricing Strategy (Margin/Markups) ]]
--_ [[ /use-case/construction-project-quotations/estimating-and-pricing/ Estimating & Pricing ]]
@endmindmap
