@startmindmap

!include ../../../../include/themes/light.puml

+ [[ /use-case/client-360/know-your-customer/anti-money-laundering/transaction-based-aml/ Transaction / Finance based AML ]]
@endmindmap
