@startmindmap correspondent-based-aml

!include ../../../../../include/themes/light.puml

+[ [[ /use-case/client-360/know-your-customer/anti-money-laundering/correspondent-based-aml/ Correspondent-based AML ]]
--_ [[ /use-case/client-360/know-your-customer/anti-money-laundering/ Anti Money Laundering (AML) ]]
@endmindmap
