@startmindmap traceability-and-provenance

!include ../../../../include/themes/light.puml

+[ [[ /use-case/construction-project-quotations/knowledge-capture-and-improvement/traceability-and-provenance/ Traceability & Provenance ]]
--_ [[ /use-case/construction-project-quotations/knowledge-capture-and-improvement/ Knowledge Capture & Continuous Improvement ]]
@endmindmap
