@startmindmap subcontractor-scope-packages

!include ../../../../include/themes/light.puml

+[ [[ /use-case/construction-project-quotations/supply-chain-and-subcontractors/subcontractor-scope-packages/ Subcontractor Scope Packages ]]
--_ [[ /use-case/construction-project-quotations/supply-chain-and-subcontractors/ Supply Chain & Subcontractors ]]
@endmindmap
