@startmindmap

!include ../../../../include/themes/light.puml

+ [[ /use-case/client-360/customer-relationship-management/contact-management/contact-relationships/ Contact Relationships ]]
@endmindmap
