@startmindmap

!include ../../../../include/themes/light.puml

+ [[ /use-case/legal-entity-management/ownership-and-capital-structure/corporate-actions/merger-and-acquisition-history/ Merger & Acquisition History ]]
@endmindmap
