@startmindmap sme-knowledge-capture

!include ../../../../include/themes/light.puml

+[ [[ /use-case/construction-project-quotations/knowledge-capture-and-improvement/sme-knowledge-capture/ SME Knowledge Capture ]]
--_ [[ /use-case/construction-project-quotations/knowledge-capture-and-improvement/ Knowledge Capture & Continuous Improvement ]]
@endmindmap
