@startmindmap relationships-and-connections

!include ../../../include/themes/light.puml

+[ [[ /use-case/client-360/relationships-and-connections/ Relationships & Connections ]]
--_ [[ /use-case/client-360/ Client 360 / Customer 360 ]]
++_ [[ /use-case/client-360/relationships-and-connections/business-connections/ Business Connections ]]
++_ [[ /use-case/client-360/relationships-and-connections/family-connections/ Family Connections ]]
++_ [[ /use-case/client-360/relationships-and-connections/political-connections/ Political Connections ]]
++_ [[ /use-case/client-360/relationships-and-connections/social-connections/ Social Connections ]]
@endmindmap
