@startmindmap forecasting

!include ../../../../../include/themes/light.puml

+ [[ /use-case/client-360/customer-relationship-management/opportunity-management/forecasting/ Forecasting ]]
--_ [[ /use-case/client-360/customer-relationship-management/opportunity-management/ Opportunity Management ]]
---_ [[ /use-case/client-360/customer-relationship-management/opportunity-management/sales-pipeline/ Sales Pipeline ]]
@endmindmap
