@startmindmap legal-entities

!include ../../../../../include/themes/light.puml

+[ [[ /use-case/client-360/know-your-customer/core-record-management/legal-entities/ Legal Entities ]]
--_ [[ /use-case/client-360/know-your-customer/core-record-management/ Core Record Management ]]
@endmindmap
