@startmindmap bid-no-bid-decisioning

!include ../../../../include/themes/light.puml

+ [[ /use-case/construction-project-quotations/opportunity-and-tender-intake/bid-no-bid-decisioning/ Bid/No-Bid Decisioning ]]
--_ [[ /use-case/construction-project-quotations/opportunity-and-tender-intake/ Opportunity & Tender Intake ]]
---_ [[ /use-case/construction-project-quotations/opportunity-and-tender-intake/rfp-rfq-intake/ RFP/RFQ Intake & Document Catalog ]]
---_ [[ /use-case/construction-project-quotations/opportunity-and-tender-intake/site-visit-and-existing-conditions/ Site Visit & Existing Conditions ]]
@endmindmap
