@startmindmap contact-relationships

!include ../../../../../include/themes/light.puml

+[ [[ /use-case/client-360/customer-relationship-management/contact-management/contact-relationships/ Contact Relationships ]]
--_ [[ /use-case/client-360/customer-relationship-management/contact-management/ Contact Management ]]
@endmindmap
