@startmindmap stock-splits

!include ../../../../../include/themes/light.puml

+ [[ /use-case/legal-entity-management/ownership-and-capital-structure/corporate-actions/stock-splits/ Stock Splits ]]
--_ [[ /use-case/legal-entity-management/ownership-and-capital-structure/corporate-actions/ Corporate Actions ]]
---_ [[ /use-case/legal-entity-management/ownership-and-capital-structure/corporate-actions/dividends/ Dividends ]]
---_ [[ /use-case/legal-entity-management/ownership-and-capital-structure/corporate-actions/merger-and-acquisition-history/ Merger & Acquisition History ]]
---_ [[ /use-case/legal-entity-management/ownership-and-capital-structure/corporate-actions/parents-and-subsidiaries/ Parents & Subsidiaries ]]
---_ [[ /use-case/legal-entity-management/ownership-and-capital-structure/corporate-actions/spin-offs/ Spin-offs ]]
@endmindmap
