title: Complex Construction Project Quotations
nav:
  - index.md
  - estimating-and-pricing
  - knowledge-capture-and-improvement
  - opportunity-and-tender-intake
  - proposal-submission-and-negotiation
  - risk-compliance-and-contracts
  - scope-and-requirements
  - supply-chain-and-subcontractors
