title: Legal Entity Management
nav:
  - index.md
  - compliance-and-documentation
  - contact-and-location-information
  - corporate-governance
  - financial-information
  - identification-and-registration
  - lifecycle-and-status
  - ownership-and-capital-structure
  - supporting-information
