@startmindmap

!include ../../../include/themes/light.puml

+ [[ /use-case/construction-project-quotations/opportunity-and-tender-intake/rfp-rfq-intake/ RFP/RFQ Intake & Document Catalog ]]
@endmindmap
