title: Govern (Cybersecurity Governance)
nav:
- index.md
- compliance-and-audit.md
- risk-management.md
- security-architecture-and-standards.md
- security-strategy-and-policy.md
- third-party-and-supply-chain-risk.md
