@startmindmap

!include ../../../include/themes/light.puml

+ [[ /use-case/construction-project-quotations/scope-and-requirements/assumptions-exclusions-qualifications/ Assumptions, Exclusions & Qualifications ]]
@endmindmap
