@startmindmap

!include ../../../include/themes/light.puml

+ [[ /use-case/construction-project-quotations/scope-and-requirements/scope-decomposition-wbs-boq/ Scope Decomposition (WBS/BoQ) ]]
@endmindmap
