name: test

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level (this is just a test input)'
        required: true
        default: 'warning'

jobs:

  integration-test:
    runs-on: ubuntu-latest
    services:
      triple-store:
        image: "stardog/stardog:7.6.2-java11-preview"
        ports:
          - 5820:5820
      psvc-story:
        image: "docker.io/agnosai/psvc-story:main"
        ports:
          - 8080:8080
        credentials:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

    steps:
      - name: Test Triple Store
        run: |
          curl -vvv --user admin:admin http://localhost:5820/admin/databases

      - name: Test Story Service
        run: |
          curl -vvv --user admin:admin http://localhost:8080/query/get-stories

