@startmindmap

!include ../../../include/themes/light.puml

+ [[ /use-case/construction-project-quotations/proposal-submission-and-negotiation/negotiation-support-and-revisions/ Negotiation Support & Revisions ]]
@endmindmap
