@startmindmap

!include ../../../include/themes/light.puml

+ [[ /use-case/construction-project-quotations/proposal-submission-and-negotiation/proposal-document-generation/ Proposal Document Generation & Assembly ]]
@endmindmap
